export const SECTION_A = "Neurodegeneration"
export const SECTION_B = "Neuroimaging"
export const SECTION_C = "Neurodevelopment"


export const availableIssues = (sectionTitle: string) => {
    switch(sectionTitle) {
        case SECTION_A:
            return [
                "Alpha- synuclein",
                "Alzheimer’s Disease",
                "APP processing",
                "Astroglial hypothesis of Alzheimer’s Disease",
                "FUS gene",
                "Misfolded protein",
                "Neurofibrillary tangles",
                "Parkinson’s disease",
                "Prion Diseases",
                "Tau protein ",
                "The amyloid beta hypothesis",
                "APOE4",
                "Adeno-associated virus",
                "Amyotrophic lateral sclerosis",
                "Antisense olgionucleotides",
                "C9ORF72",
                "Dipeptide repeat proteins",
                "Fasciculations",
                "Frontotemporal dementia",
                "Fused in sarcoma",
                "Haploinsufficiency",
                "Lower motor neurone",
                "Intracellular protein clearance pathways",
                "Q331K mutation",
                "RNA foci",
                "Stress granules",
                "Superoxide dismutase 1 ",
                "TDP-43",
                "Upper motor neurone",
                "Ataxia",
                "Autophagy",
                "Autosomal dominant",
                "Bradykinesia",
                "Chorea",
                "DRPLA",
                "Dysphagia",
                "Dystonia",
                "Huntington’s disease",
                "Neurodegeneration",
                "Polyglutamine diseases",
                "Protein aggregates",
                "Spinal and bulbar muscular atrophy",
                "Spinocerebellar ataxias",
                "Ubiquitin proteosome system ",
            ]
        case SECTION_B:
            return [
                "Amphetamine – can be used to treat ADHD. ",
                "Apparent diffusion coefficient- the diffusion rate of water molecules in a tissue, as calculated with MRI ",
                "Arterial spin labelling- measure cerebral blood perfusion ",
                "BOLD signal- measures oxygen consumption with MRI. ",
                "Cerebral blood flow- a critical marker in determining BOLD response in MRI. ",
                "Cognitive neuroscience",
                "Diffusion weighted imaging – the method to generate images in MRI. ",
                "Electroencephalography- the electrical activity of the cortex in poor spatial resolution but high temporal resolution",
                "Magnetic resonance angiography- MRI used for blood vessels",
                "MRI",
                "Magnetoencephalography- the electrical activity of neurons- high temporal and spatial resolution. ",
                "Near-infrared spectroscopy imaging- monitors brain activity via changes in haemoglobin concentration, people can move with it. ",
                "PET",
                "Ultrasound",
                "Venogram or venography- diagnose health conditions of veins- only really used for detecting deep vein thrombosis",
                "Fourier transformation- used to acquire MRI signal.",
                "Functional neuroimaging- with the goal of finding the function of different brain areas",
                "Granger causality- a statistical concept",
                "Haemodynamic response- the way that the body rapidly delivers blood to active neuronal tissue, utilised in functional neuroimaging",
                "Machine learning- useful in modelling highly dimensional datasets- such as image analysis",
                "Pre-processing- removes noise from data. ",
                "Pulse-sequence- used in MRI. ",
                "Signal to noise ratio",
                "Spatial resolution",
                "Temporal resolution",
                "Transcranial magnetic stimulation- a technique for non-invasive brain stimulation",
                "Voxel based morphometry- measures brain tissue concentration ",
                "Dose optimisation- to obtain maximal therapeutic benefit and minimal adverse effects",
                "Drug effect",
                "Occupancy- the fraction of receptors linked to their endogenous ligand",
                "Pharmacodyanmics",
                "Pharmokinetics- absorption, distribution, metabolism, excretion",
                "Pharmacological imaging- any imaging technique to understand drug metabolism ",
                "Radioligand",
                "Receptor density- can be measured via PET",
                "Receptor availability- usually mapped with PET",
                "Tractography- a 3D modelling technique providing a computational reconstruction of in vivo nerve tracts                ",
            ]
        case SECTION_C:
            return [
                "Cortical GABAergic neurons",
                "Cortical plate development",
                "Intermediate zone",
                "Marginal zone",
                "Neocortex",
                "Neural progenitor cells",
                "Neuroepithelial cells",
                "Neurogenesis",
                "Neuronal migration",
                "Pre-plate",
                "Reelin",
                "RELN-Dab1 pathway",
                "Somal translocation",
                "Subplate",
                "Subventricular zone",
                "Ventricular zone",
                "Areal diversity- the neural differences depending on the specific area of the cortical sheet",
                "Fate determination",
                "French flag model",
                "Histological diversity",
                "Interneuons",
                "Laminar diversity- withint the 6 neocortical layers and the 3 layers of phylogeneitcally older parts of the cortex",
                "Morphogens",
                "Neuronal birth-dating – to determine the route/rate of cell migration- where a cell has come from",
                "Neuronal development",
                "Positional specification",
                "Progenitor cells",
                "Blastula",
                "Conditional specification- how a cells fate can be determined by certain conditions such as psoiton",
                "Ectoderm",
                "Floor plate",
                "Gastrulation",
                "Midbrain-hindbrain boundary",
                "Neural tube",
                "Neuralation",
                "Nieuwkoop centre",
                "Notochord",
                "Rhombomeres",
                "Somites- blocks of mesoderm situated along the notochord that go on to form muscle, skeleton and skin. ",
                "Sonic hedgehog- important for ventral to dorsal patterning- highest in ventral areas. ",
                "Specificatio",
                "Spemann’s organiser",
                "Wnt- a posteriorizing signal- a shift from forebrain to hindbrain fate.                 ",
            ]
    }
    throw "Invalid section name"
}
